name: Fetch and Organize Streams
# https://github.com/qq254950134/my-iptv

# 触发条件
on:
  schedule:
    - cron: '0 2,6,12,18,21 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 确保 GITHUB_TOKEN 具有写入权限

env:
  TZ: Asia/Shanghai # 设置时区为北京时间

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
    # 检出项目仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    # 运行 Python 脚本
    - name: Run script
      run: |
        python py/get_iptv.py

    # 列出当前目录中的文件
    #- name: List files in workspace
    #  run: ls -la

    # 检查 Git 状态，确保文件已经被添加
    - name: Git status
      run: git status

    # 配置 Git 信息
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # 提交并推送文件到项目仓库
    - name: Commit and Push changes
      run: |
        git add $(pwd)/lib/iptv.txt
        git add $(pwd)/lib/iptv.m3u
        git commit -m "Update m3u" --allow-empty
        git push origin HEAD:main

    # 上传输出文件作为 GitHub Action 的工件 (artifact)
    - name: Upload streams file
      uses: actions/upload-artifact@v4
      with:
        name: iptv
        path: iptv.m3u